### PR TITLE
doc: add jupyter notebook with intent classification example

### PR DESCRIPTION
**Pull request by thompsgj**
This pull request resolves [Issue 3498](https://github.com/langfuse/langfuse/issues/3498).  It adds a Jupyter notebook that gives with an intent classification example that:
* [x] retrieves trace data from a project
* [x] trains a basic intent classification model on a small dataset
* [x] uploads labels as tags on traces in Langfuse

### CODE REVIEW

**Comment by marcklingen** [comment]
This is super nice, thank you!

What do you think about adding embedding+llm-summarization based intent classification as a secondary technique? This would work unsupervised for unseen data which is most likely more useful for everyone who wants to use this to understand which use cases exist in their application. I found this example which seems to summarize the technique well, have not found an open source library for this yet though: https://rasa.com/docs/rasa/next/llms/llm-intent

**Comment by thompsgj** [comment]
> This is super nice, thank you!
> 
> What do you think about adding embedding+llm-summarization based intent classification as a secondary technique? This would work unsupervised for unseen data which is most likely more useful for everyone who wants to use this to understand which use cases exist in their application. I found this example which seems to summarize the technique well, have not found an open source library for this yet though: https://rasa.com/docs/rasa/next/llms/llm-intent

That sounds great!  I'll look into that technique a bit and update the notebook accordingly.

**Comment by thompsgj** [comment]
> Really looking forward to this! I think this is a great addition to the Langfuse docs and a notebook which we should probably feature in the main documentation once finished

Thank you, Marc!  Happy that this seems like a promising resource for the community.  I've updated the notebook with a basic unsupervised intent classification approach.  It uses ChromaDB, a clustering algorithm, and OpenAI to work in similar way to what the article outlined.

**Comment by marcklingen** [comment]
awesome! will try to have a look later today (need to get some things done before)

**Comment by marcklingen** [comment]
this is awesome, I just spent some time on this to use prod data of the langfuse demo project for the unsupervised example. I removed chroma as i think keeping it in pandas makes it more understandable. I'll merge this now and might make slight edits over the coming days when i have time to showcase it more prominently in the docs!

thanks again for the contribution, this will be helpful for many people!

**Pull request merged**
