### PR TITLE
Add anthropic_joke_example.py in the cookbook

### LINKED ISSUE #882: Add anthropic_joke_example.py in the cookbook
Hi there,
I would like to add the [anthropic_joke_example.py](https://github.com/traceloop/openllmetry/blob/main/packages/sample-app/sample_app/anthropic_joke_example.py) in the [Cookbook](https://langfuse.com/guides)

### PR DESCRIPTION
**Pull request by RS-labhub**
Fixes #882

### CODE REVIEW

**Comment by RS-labhub** [comment]
@marcklingen you may review this

(sorry for the late PR, was busy in the festival)

**Comment by marcklingen** [comment]
Thanks for opening the PR. How does this integrate with Langfuse though? For traceability in Langfuse you need to wrap the anthropic sdk with the Langfuse `observe` decorator. See this notebook for an example using Mistral SDK: https://github.com/langfuse/langfuse-docs/blob/main/cookbook/integration_mistral_sdk.ipynb

**Review by marcklingen — CHANGES_REQUESTED** [review]
Thanks for opening the PR.

How does this example integrate with Langfuse? For traceability in Langfuse you need to wrap the anthropic sdk with the Langfuse observe decorator. See this notebook for an example using Mistral SDK: https://github.com/langfuse/langfuse-docs/blob/main/cookbook/integration_mistral_sdk.ipynb

**Comment by RS-labhub** [comment]
Ahh sorry, I ran down into some confusion. Will be fixing it. Sorry 😅

**Comment by marcklingen** [comment]
sounds good, thank you!

**Comment by marcklingen** [comment]
closing this PR as it is unrelated to langfuse

**Comment by marcklingen** [comment]
feel free to reopen in case you make changes!

**Pull request closed without merging**
