### PR TITLE
docs: add deploy to Zeabur button

### PR DESCRIPTION
**Pull request by MichaelYuhe**
[Zeabur](https://zeabur.com) is a platform for hosting full stack services, and there is a template made by the community to deploy Langfuse with one click.
https://zeabur.com/templates/NU78ME

### CODE REVIEW

**Comment by marcklingen** [comment]
Hi @MichaelYuhe, did you test whether the template works? The description of the template still includes a reference to railway

**Comment by MichaelYuhe** [comment]
Yeah it works, I didn't notice the railway references(it's made by one of our users and his deployment just works) I will ask him for help modifying the references.

**Review by marcklingen — COMMENTED** [review]
I've just reviewed the configuration of the example within your repo and it does not match the deployment guide of Langfuse. I'll close this PR for now, please reopen if you update the template

https://github.com/zeabur/zeabur/blob/main/prebuilts/langfuse.toml

**Comment by marcklingen** [comment]
- It uses a fixed sha instead of the latest `2` version
- It does not include the optional environment variables

**Pull request closed without merging**
