### PR TITLE
fix: fix broken `docker-compose` command in local deployment docs

### PR DESCRIPTION
**Pull request by elliottower**
Since v2.3.4 (2022) the command has been changed to `docker compose` rather than `docker-compose`, see https://docs.docker.com/compose/release-notes/#234

Trying to use `docker-compose` with an updated version of docker will say `unknown command: docker-compose`

### CODE REVIEW

**Comment by elliottower** [comment]
> ## **Disclaimer**: Experimental PR review
> ## PR Summary
> This pull request updates the Docker Compose command in the local deployment documentation to align with the latest syntax.
> 
> * Updated `docker-compose pull` to `docker compose pull` in `/pages/docs/deployment/local.mdx`
> * Inconsistency remains on line 44, which still mentions `docker-compose pull`
> * Change reflects Docker Compose syntax update from v2.3.4 (2022) onwards
> * Addresses potential "unknown command" error for users with updated Docker versions
> 
> 1 file(s) reviewed, no comment(s) [Edit PR Review Bot Settings](https://app.greptile.com/apps/github)

Oh I see line 

> ## **Disclaimer**: Experimental PR review
> ## PR Summary
> This pull request updates the Docker Compose command in the local deployment documentation to align with the latest syntax.
> 
> * Updated `docker-compose pull` to `docker compose pull` in `/pages/docs/deployment/local.mdx`
> * Inconsistency remains on line 44, which still mentions `docker-compose pull`
> * Change reflects Docker Compose syntax update from v2.3.4 (2022) onwards
> * Addresses potential "unknown command" error for users with updated Docker versions
> 
> 1 file(s) reviewed, no comment(s) [Edit PR Review Bot Settings](https://app.greptile.com/apps/github)

This actually pointed out another instance of it I missed, cool feature to have a bot like this.

**Comment by marcklingen** [comment]
glad to see that the ai summary actually helped here :)

**Comment by elliottower** [comment]
Cheers, thanks for the help with this and the other (I wasn’t sure if I should rebase to update or merge, I feel like in repos I’ve worked in there’s a setting that makes it so you don’t have to update your branch if it doesn’t conflict with anything)

**Comment by marcklingen** [comment]
thanks again!

We like to make sure that the checks pass before merging as sometimes there are dependency conflicts and a quick update by merging main / rebasing is worth the one-click effort I guess

**Pull request merged**
