### PR TITLE
feat: add LANGFUSE_S3_EVENT_UPLOAD options

### PR DESCRIPTION
**Pull request by Steffen911**
@marcklingen Do you think it makes sense to document this functionality already? Will probably have little use for self-hosters right now, but will become mandatory for V3. So we could get this written down now, even though we expect no one to make use of it.

### CODE REVIEW

**Comment by marcklingen** [comment]
I think continuously documenting these options makes sense. I’d suggest to merge them to a v3 branch though as this otherwise might be confusing, thereby we can also collaborate on preview and final docs for v3 and share with early adopters once we release the alpha version

**Comment by Steffen911** [comment]
@maxdeichmann You had an idea on the "V3 branch". Do you have a ticket to execute on it? Otherwise, I could also move this into a draft PR/label it V3 and we keep it sitting until it becomes relevant.

**Comment by maxdeichmann** [comment]
Yes, i would create a "hidden" page which we can send around. This way we do not have a V3 branch. I already see merge conflicts incoming.

langfuse.com/docs/v3 would be the path for it.

**Comment by marcklingen** [comment]
Sounds good to me, good approach. Let me quickly add noindex headers to this page before merging. I can merge once done

**Pull request merged**
